subjects = [ 
    {
        id:'0',
        subject:'IT',
        location:'Hendon',
        price:1000,
        img:'public/img/it.jpeg',
        space: 8,
        showSpace:8,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    },
    {
        id:'1',
        subject:'Maths',
        location:'London',
        price:1000,
        img:'public/img/math.jpg',
        space: 1,
        showSpace:1,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'2',
        subject:'History',
        location:'Madrid',
        price:1000,
        img:'public/img/history.jfif',
        space: 5,
        showSpace:5,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'3',
        subject:'Arts',
        location:'Bratislava',
        price:1000,
        img:'public/img/arts.jpg',
        space: 6,
        showSpace:6,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'4',
        subject:'Dance',
        location:'Prague',
        price:1000,
        img:'public/img/dance.jpg',
        space: 3,
        showSpace:3,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'5',
        subject:'Graphics',
        location:'Dubai',
        price:1000,
        img:'public/img/graphics.webp',
        space: 12,
        showSpace:12,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'6',
        subject:'Game dev',
        location:'New York',
        price:1000,
        img:'public/img/gamedev.jfif',
        space: 1,
        showSpace:1,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'7',
        subject:'Politics',
        location:'Manchester',
        price:1000,
        img:'public/img/politics.jpg',
        space: 5,
        showSpace:5,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'8',
        subject:'Economics',
        location:'Moscow',
        price:1000,
        img:'public/img/eco.jpg',
        space: 5,
        showSpace:5,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    },
    {
        id:'9',
        subject:'Geography',
        location:'Helsinki',
        price:1000,
        img:'public/img/geo.png',
        space: 0,
        showSpace:0,
        countItemsInCart:0,
        available:false,
        totalPrice:0,
    },
]