subjects = [ 
    {
        id:'0',
        subject:'IT',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 8,
        showSpace:8,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    },
    {
        id:'1',
        subject:'Maths',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 1,
        showSpace:1,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'2',
        subject:'History',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 5,
        showSpace:5,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'3',
        subject:'Arts',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 6,
        showSpace:6,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'4',
        subject:'Dance',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 3,
        showSpace:3,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'5',
        subject:'Graphics',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 12,
        showSpace:12,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'6',
        subject:'Game dev',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 1,
        showSpace:1,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'7',
        subject:'Politics',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 5,
        showSpace:5,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    }, 
    {
        id:'8',
        subject:'Economics',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 5,
        showSpace:5,
        countItemsInCart:0,
        available:true,
        totalPrice:0,
    },
    {
        id:'9',
        subject:'Geography',
        location:'Hendon',
        price:1000,
        img:'public/img/image1.jpeg',
        space: 0,
        showSpace:0,
        countItemsInCart:0,
        available:false,
        totalPrice:0,
    },
]